plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
base = "enjifano-portfolio-showcase"
publish = "dist"
command = "npm run build"
publishOrigin = "ui"
commandOrigin = "ui"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]